import numpy as np
import torch
from typing import Tuple, Dict, Any

def inverse_fft_from_real_imag(
    x_transformed: np.ndarray,
    norm: str = 'realimag',
    device: str = 'cpu',
    channel_first: bool = True,
    shift: bool = True,
    stack_type: str = 'alternate'): 
    """
    Reconstructs the original input from the FFT output generated by fft_real_imag_normalized.

    Args:
        x_transformed (np.ndarray): The real+imag FFT output array (shape: (2C, H, W) or (H, W, 2C)).
        norm (str): Normalization method used during FFT: 'realimag', 'softmax', or 'none'.
        device (str): Device to use for torch operations ('cpu' or 'cuda').
        channel_first (bool): Whether channels are the first dimension.
        shift (bool): If True, applies ifftshift before inverse FFT.
        stack_type (str): 'alternate' (interleaved real/imag) or any other (stacked real + imag).

    Returns:
        np.ndarray: Reconstructed real-valued approximation of the original input image.
    """
    # Determine spectral dimension index
    dim = 0 if channel_first else -1

    # Get original number of spectral channels (C)
    C = x_transformed.shape[dim] // 2

    # Convert input array to a PyTorch tensor on the chosen device
    x_tensor = torch.tensor(x_transformed, dtype=torch.float32, device=device)

    # === NOTE ===
    # The original fft_real_imag_normalized may have applied normalization (e.g. minmax or softmax).
    # Unless the original min/max were saved, we cannot recover exact values.
    # Here we assume data is already scaled reasonably in [0.0001, 1] and proceed directly.
    if norm in ('realimag', 'softmax'):
        pass  # Skipping inverse normalization due to unavailable original scale info

    # Split into real and imaginary parts based on stacking format
    if stack_type == 'alternate':
        # Interleaved format: even indices = real, odd indices = imag
        if channel_first:
            real = x_tensor[0::2]  # Extract even channels
            imag = x_tensor[1::2]  # Extract odd channels
        else:
            real = x_tensor[..., 0::2]  # Last axis: even
            imag = x_tensor[..., 1::2]  # Last axis: odd
    else:
        # Stacked format: real then imag along spectral dimension
        real, imag = torch.tensor_split(x_tensor, 2, dim=dim)

    # Reconstruct the complex-valued tensor from real and imaginary parts
    complex_tensor = torch.complex(real, imag)

    # If FFT was shifted during the forward transform, apply inverse shift
    if shift:
        complex_tensor = torch.fft.ifftshift(complex_tensor, dim=dim)

    # Apply inverse FFT along the spectral/channel dimension
    ifft_result = torch.fft.ifft(complex_tensor, dim=dim)

    # Return only the real part since original input was real-valued
    return ifft_result.real.cpu().numpy()



class InverseFourierSpectralTransform:
    """
    Transform class to apply 1D FFT along the spectral dimension of a hyperspectral image.
    """
    def __init__(self, 
                 norm: str = 'abs',
                 transf_cube: bool = False,
                 channel_first: bool = True, 
                 device: str = 'cpu', 
                 shift: bool = True, 
                 stack_type:str = 'alternate' 
                 ):
        self.channel_first = channel_first
        self.norm = norm
        self.transf_cube = transf_cube
        self.device = device
        self.shift = shift
        self.stack_type = stack_type

    def __call__(self,
                 x: np.ndarray,
                 cube: np.ndarray,
                 meta: Dict[str, Any]
                 ) -> Tuple[torch.Tensor, np.ndarray, Dict[str, Any]]:
        """
        Apply the spectral FFT transform.

        Args:
            x (np.ndarray): Hyperspectral image [C, W, H C]
            cube (np.ndarray): Extra cube (unchanged)
            meta (dict): Metadata (unchanged)
        
        Returns:
            Tuple[torch.Tensor, np.ndarray, Dict[str, Any]]: Transformed image, original cube, metadata
        """
        x_transformed = inverse_fft_from_real_imag(x, self.norm, self.device, self.channel_first, self.shift, self.stack_type)

        if self.transf_cube: 
            cube = inverse_fft_from_real_imag(cube, self.norm, self.device, self.channel_first, self.shift, self.stack_type)

        return x_transformed, cube, meta

    def __str__(self):
        return f"FourierSpectralTransform(norm={self.norm}, transform cube={self.transf_cube}, device={self.device})"
