import torch

def inverse_fft_from_real_imag(
    y_transformed: torch.Tensor,
    norm: str = 'realimag',
    device: str = 'cpu',
    channel_first: bool = True,
    shift: bool = True,
    stack_type: str = 'alternate'
) -> torch.Tensor:
    """
    Reconstructs the original input from the FFT output generated by fft_real_imag_normalized.

    Args:
        y_transformed (torch.Tensor): Real+imag FFT output tensor (shape: (2C, H, W) or (H, W, 2C)).
        norm (str): Normalization used in FFT: 'realimag', 'softmax', or 'none'.
        device (str): Device for computation ('cpu' or 'cuda').
        channel_first (bool): Whether channels are the first axis.
        shift (bool): If True, applies ifftshift before inverse FFT.
        stack_type (str): 'alternate' for interleaved real/imag, else stacked format.

    Returns:
        torch.Tensor: Reconstructed real-valued tensor (same shape as original input).
    """
    # Spectral (channel) axis
    dim = 0 if channel_first else -1

    # Recover number of original spectral channels
    C = y_transformed.shape[dim] // 2

    # Ensure tensor is on the correct device
    x_tensor = y_transformed.to(device)

    # Split into real and imaginary components
    if stack_type == 'alternate':
        if channel_first:
            real = x_tensor[0::2]
            imag = x_tensor[1::2]
        else:
            real = x_tensor[..., 0::2]
            imag = x_tensor[..., 1::2]
    else:
        real, imag = torch.tensor_split(x_tensor, 2, dim=dim)

    # Combine into complex tensor
    complex_tensor = torch.complex(real, imag)

    # Undo FFT shift if applied during forward FFT
    if shift:
        complex_tensor = torch.fft.ifftshift(complex_tensor, dim=dim)

    # Perform inverse FFT along spectral dimension
    ifft_result = torch.fft.ifft(complex_tensor, dim=dim)

    # Return only real part (original data is real)
    return ifft_result.real

def inverse_fft_from_real_imag(
    y_transformed: torch.Tensor,
    norm: str = 'realimag',
    device: str = 'cpu',
    channel_first: bool = True,
    shift: bool = True,
    stack_type: str = 'alternate'
) -> torch.Tensor:
    """
    Reconstructs the original input from the FFT output generated by fft_real_imag_normalized.

    Args:
        y_transformed (torch.Tensor): Real+imag FFT output tensor (shape: (2C, H, W) or (H, W, 2C)).
        norm (str): Normalization used in FFT: 'realimag', 'softmax', or 'none'.
        device (str): Device for computation ('cpu' or 'cuda').
        channel_first (bool): Whether channels are the first axis.
        shift (bool): If True, applies ifftshift before inverse FFT.
        stack_type (str): 'alternate' for interleaved real/imag, else stacked format.

    Returns:
        torch.Tensor: Reconstructed real-valued tensor (same shape as original input).
    """
    # Spectral (channel) axis
    dim = 0 if channel_first else -1

    # Recover number of original spectral channels
    C = y_transformed.shape[dim] // 2

    # Ensure tensor is on the correct device
    x_tensor = y_transformed.to(device)

    # Split into real and imaginary components
    if stack_type == 'alternate':
        if channel_first:
            real = x_tensor[0::2]
            imag = x_tensor[1::2]
        else:
            real = x_tensor[..., 0::2]
            imag = x_tensor[..., 1::2]
    else:
        real, imag = torch.tensor_split(x_tensor, 2, dim=dim)

    # Combine into complex tensor
    complex_tensor = torch.complex(real, imag)

    # Undo FFT shift if applied during forward FFT
    if shift:
        complex_tensor = torch.fft.ifftshift(complex_tensor, dim=dim)

    # Perform inverse FFT along spectral dimension
    ifft_result = torch.fft.ifft(complex_tensor, dim=dim)

    # Return only real part (original data is real)
    return ifft_result.real

class InverseFourierSpectralTransform:
    """
    Inverse FFT transform class for hyperspectral data transformed with real+imag FFT.
    """
    def __init__(self, 
                 norm: str = 'realimag',
                 channel_first: bool = True, 
                 device: str = 'cpu', 
                 shift: bool = True, 
                 stack_type: str = 'alternate'):
        self.channel_first = channel_first
        self.norm = norm
        self.device = device
        self.shift = shift
        self.stack_type = stack_type

    def __call__(self, cube: torch.Tensor) -> torch.Tensor:
        """
        Apply inverse FFT transform to a single cube.

        Args:
            cube (torch.Tensor): Input real+imag transformed tensor (2C, H, W) or (H, W, 2C)

        Returns:
            torch.Tensor: Reconstructed real-valued tensor.
        """
        return inverse_fft_from_real_imag(
            y_transformed=cube,
            norm=self.norm,
            device=self.device,
            channel_first=self.channel_first,
            shift=self.shift,
            stack_type=self.stack_type
        )

    def __str__(self):
        return f"InverseFourierSpectralTransform(norm={self.norm}, device={self.device})"