save_checkpoint_path: 'models/'  # modificado

fixed_checkpoint_name: 'test_ifft.pth'
pretrained_path: null
continue_model_path: null
resume_wandb_id: 'vo2sayaq'

evaluate_step: 20   # will never happen if higher than dataset size
save_steps: 20

wandb: True

train:
  batch_size: 5  
  lr: 0.0001  # 1e-4 faster initial lr 
  epochs: 50 
  transform_index: "downs4_fft_cie_minmax_gpu_shift" # nnunet transform simply doesnt work 

valid:
  batch_size: 5
  transform_index: "downs4_fft_cie_minmax_gpu_shift"

nworkers: 8

task: 'recon'
loss: "MSE"  
model: 'seg-rec_31to61' 
base_path: "DATA_PATH" #"/media/ana-caznok/SSD-08/icasp_4090/icasp/data/Link_2" # variavel de ambiente
preprocessing: h5py
opt: "AdamW"  # adamW with 1e-5 weight decay
scheduling: 0.998  # exponential learning rate decay
ifft: False

# Minimize sam instead of loss
torchinfo: True
