save_checkpoint_path: 'models/'  # modificado

fixed_checkpoint_name: 'fft2hsi_1000.pth'
pretrained_path: null
continue_model_path: null
resume_wandb_id: 'vo2sayaq'

evaluate_step: 20   # will never happen if higher than dataset size
save_steps: 20

wandb: True

train:
  batch_size: 20  
  lr: 0.0001  # 1e-4 faster initial lr 
  epochs: 1000 
  transform_index: "fft_D40_minmax_gpu_shift" 

valid:
  batch_size: 6
  transform_index: "fft_D40_minmax_gpu_shift"

nworkers: 25

task: 'recon'
loss: "MRAESSIMSAMLoss"  
model: 'seg-rec_31to61_patch16' 
base_path: "DATA_PATH" #"/media/ana-caznok/SSD-08/icasp_4090/icasp/data/Link_2" # variavel de ambiente
preprocessing: 'downsampled'
opt: "AdamW"  # adamW with 1e-5 weight decay
scheduling: 0.998  # exponential learning rate decay
ifft: False

# Minimize sam instead of loss
torchinfo: True
